meta:
  id: tokyo_micro_mean_reversion_v0
  name: Tokyo Micro Mean Reversion (USDJPY)
  version: "0.1"
  category: scalping
  tags: [scalping, mean_reversion, tokyo]
  description: |
    Contrarian scalping strategy targeting Tokyo session microstructure. Uses
    micro z-score and trend filters to fade short-lived excursions during tight
    spread conditions.

strategy:
  class_path: strategies.tokyo_micro_mean_reversion.TokyoMicroMeanReversion
  instruments:
    - symbol: USDJPY
      timeframe: 1m
      mode: conservative
  parameters:
    zscore_threshold: 1.8
    trend_filter: 0.4
    atr_tp_mult: 0.4
    atr_sl_mult: 0.7
    cooldown_bars: 3
    default_tp_pips: 3.5
    default_sl_pips: 6.0

router:
  allowed_sessions: [TOK]
  allow_spread_bands: [narrow, normal]
  allow_rv_bands: [low, mid]
  max_latency_ms: 35
  category_cap_pct: 15
  tags: [tokyo, micro, mean_reversion]
  priority: 0.1
  max_gross_exposure_pct: 20.0
  max_correlation: 0.6
  correlation_tags: [tokyo, scalping]
  max_reject_rate: 0.05
  max_slippage_bps: 10.0

risk:
  risk_per_trade_pct: 0.04
  max_daily_dd_pct: 2.5
  notional_cap: 500000
  max_concurrent_positions: 2
  warmup_trades: 15

features:
  required:
    - micro_zscore
    - micro_trend
    - mid_price
    - spread_band
    - rv_band
    - atr14
  optional:
    - session
    - liquidity_score

runner:
  runner_config:
    threshold_lcb_pip: 0.25
    allowed_sessions: [TOK]
    warmup_trades: 15
    include_expected_slip: true
    cooldown_bars: 3
  cli_args:
    equity: 60000
    threshold_lcb: 0.25
    allowed_sessions: TOK
    mode: conservative

state:
  archive_namespace: strategies.tokyo_micro_mean_reversion.TokyoMicroMeanReversion/USDJPY/conservative
  ev_profile: configs/ev_profiles/day_orb_5m.yaml

notes:
  - Requires microstructure features (micro_zscore, micro_trend, liquidity_score).
  - Initial risk settings aim for small position size (≤0.04% of equity).
  - Adjust ATR multipliers once empirical spread/vol data has been reviewed.
