meta:
  id: day_orb_5m_v1
  name: Day ORB 5m (USDJPY)
  version: "1.0"
  category: day
  tags: [orb, breakout]
  description: |
    Opening range breakout strategy for USDJPY 5m bars. Trades LDN/NY sessions
    with ATR-based exits and EV gating via Beta-Binomial.

strategy:
  class_path: strategies.day_orb_5m.DayORB5m
  instruments:
    - symbol: USDJPY
      timeframe: 5m
      mode: conservative
  parameters:
    or_n: 6
    k_tp: 1.0
    k_sl: 0.8
    k_tr: 0.0
    require_close_breakout: false
    require_retest: false
    min_or_atr_ratio: 0.6

router:
  allowed_sessions: [LDN, NY]
  allow_spread_bands: [narrow, normal]
  allow_rv_bands: [mid, high]
  max_latency_ms: 80
  category_cap_pct: 40
  tags: [breakout, usd, jpy]

risk:
  risk_per_trade_pct: 0.25
  max_daily_dd_pct: 5.0
  notional_cap: 2000000
  max_concurrent_positions: 1
  warmup_trades: 50

features:
  required:
    - atr14
    - adx14
    - rv12
    - or_high
    - or_low
    - spread_band
    - session
  optional:
    - regime_flag

runner:
  runner_config:
    threshold_lcb_pip: 0.5
    min_or_atr_ratio: 0.6
    allowed_sessions: [LDN, NY]
    warmup_trades: 50
    include_expected_slip: true
  cli_args:
    equity: 100000
    threshold_lcb: 0.5
    min_or_atr: 0.6
    allowed_sessions: LDN,NY

state:
  archive_namespace: strategies.day_orb_5m.DayORB5m/USDJPY/conservative
  ev_profile: configs/ev_profiles/strategies.day_orb_5m.yaml

notes:
  - Disable during Tokyo session due to low OR quality.
  - Requires validated/USDJPY/5m.csv ingestion pipeline.
