meta:
  id: day_template_v0
  name: Day Strategy Template (USDJPY)
  version: "0.1"
  category: day
  tags: [template, day, usd]
  description: |
    Skeleton manifest for intraday swing/continuation strategies. Extend the
    accompanying DayStrategyTemplate class when designing new day-trade logic.

strategy:
  class_path: strategies.day_template.DayStrategyTemplate
  instruments:
    - symbol: USDJPY
      timeframe: 15m
      mode: conservative
  parameters:
    trend_lookback: 20
    pullback_threshold: 0.6
    cooldown_bars: 4
    atr_tp_mult: 1.2
    atr_sl_mult: 1.8

router:
  allowed_sessions: [LDN, NY]
  allow_spread_bands: [narrow, normal]
  allow_rv_bands: [mid, high]
  max_latency_ms: 90
  category_cap_pct: 35
  tags: [template, day, usd]
  priority: 0.0
  max_gross_exposure_pct: 40.0
  max_correlation: 0.70
  correlation_tags: [day]
  max_reject_rate: 0.04
  max_slippage_bps: 15.0

risk:
  risk_per_trade_pct: 0.18
  max_daily_dd_pct: 6.0
  notional_cap: 1500000
  max_concurrent_positions: 1
  warmup_trades: 20

features:
  required:
    - atr14
    - trend_score
    - rv_band
    - spread_band
    - session
  optional:
    - regime_flag
    - higher_tf_trend

runner:
  runner_config:
    threshold_lcb_pip: 0.45
    allowed_sessions: [LDN, NY]
    warmup_trades: 20
    include_expected_slip: true
    cooldown_bars: 4
  cli_args:
    equity: 120000
    threshold_lcb: 0.45
    allowed_sessions: LDN,NY
    mode: conservative

state:
  archive_namespace: strategies.day_template.DayStrategyTemplate/USDJPY/conservative

notes:
  - Override `_maybe_build_signal` in DayStrategyTemplate to generate orders.
  - Tune ATR multipliers and trend filters before releasing to production.
  - Document any additional feature requirements in this manifest.
