{
  "meta": {
    "strategy_key": "day_orb_5m.DayORB5m",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-10-05T13:25:19Z",
    "files_total": 66,
    "recent_count": 5,
    "latest_state_ts": "2025-10-02T21:40:13Z",
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {
      "alpha_avg": 27.851708542036196,
      "beta_avg": 22.059182342384045,
      "p_mean": 0.5580286796830178,
      "observations": 66
    },
    "recent": {
      "alpha_avg": 27.295670506363678,
      "beta_avg": 22.704329493636283,
      "p_mean": 0.545913410127274,
      "observations": 5
    }
  },
  "buckets": [
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 27.1900401892881,
        "beta_avg": 22.699636025423622,
        "p_mean": 0.5450033404159509,
        "observations": 66
      },
      "recent": {
        "alpha_avg": 26.950040284508606,
        "beta_avg": 23.049959715489884,
        "p_mean": 0.5390008056901884,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 66
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 25.013274834620407,
        "beta_avg": 19.325019866606045,
        "p_mean": 0.5641460728964055,
        "observations": 66
      },
      "recent": {
        "alpha_avg": 27.41063082026859,
        "beta_avg": 21.71395839376581,
        "p_mean": 0.5579818835907466,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 13.341239818651076,
        "beta_avg": 15.941055297493428,
        "p_mean": 0.4556077235658866,
        "observations": 66
      },
      "recent": {
        "alpha_avg": 11.55735152775598,
        "beta_avg": 18.33183574611287,
        "p_mean": 0.3866733284467791,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 66
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 26.404688384989377,
        "beta_avg": 21.751802696978142,
        "p_mean": 0.5483100573097356,
        "observations": 66
      },
      "recent": {
        "alpha_avg": 27.30390111670036,
        "beta_avg": 22.696098626315507,
        "p_mean": 0.5460780251406749,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 66
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 66
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 66
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    }
  ]
}