{
  "meta": {
    "strategy_key": "day_orb_5m.DayORB5m",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-10-02T21:40:17Z",
    "files_total": 62,
    "recent_count": 5,
    "latest_state_ts": "2025-10-02T21:40:13Z",
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {
      "alpha_avg": 28.197912174288383,
      "beta_avg": 21.707229734933172,
      "p_mean": 0.5650301972005399,
      "observations": 62
    },
    "recent": {
      "alpha_avg": 27.295670506363678,
      "beta_avg": 22.704329493636283,
      "p_mean": 0.545913410127274,
      "observations": 5
    }
  },
  "buckets": [
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 27.373730579977597,
        "beta_avg": 22.50882797116722,
        "p_mean": 0.5487635633587477,
        "observations": 62
      },
      "recent": {
        "alpha_avg": 26.950040284508606,
        "beta_avg": 23.049959715489884,
        "p_mean": 0.5390008056901884,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 62
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 24.840597872489052,
        "beta_avg": 19.163106298691392,
        "p_mean": 0.5645115187543239,
        "observations": 62
      },
      "recent": {
        "alpha_avg": 27.41063082026859,
        "beta_avg": 21.71395839376581,
        "p_mean": 0.5579818835907466,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 12.982215393752574,
        "beta_avg": 15.613786892944761,
        "p_mean": 0.4539870735634894,
        "observations": 62
      },
      "recent": {
        "alpha_avg": 11.55735152775598,
        "beta_avg": 18.33183574611287,
        "p_mean": 0.3866733284467791,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 62
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 26.586554464159434,
        "beta_avg": 21.451000570631894,
        "p_mean": 0.5534535311987476,
        "observations": 62
      },
      "recent": {
        "alpha_avg": 27.30390111670036,
        "beta_avg": 22.696098626315507,
        "p_mean": 0.5460780251406749,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 62
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 62
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 62
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    }
  ]
}