{
  "meta": {
    "strategy_key": "day_orb_5m.DayORB5m",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-10-01T12:22:26Z",
    "files_total": 52,
    "recent_count": 5,
    "latest_state_ts": "2025-10-01T12:22:22Z",
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {
      "alpha_avg": 27.31138096812492,
      "beta_avg": 22.57551900056232,
      "p_mean": 0.5474659877696868,
      "observations": 52
    },
    "recent": {
      "alpha_avg": 27.162256188228945,
      "beta_avg": 22.837743811771013,
      "p_mean": 0.5432451237645793,
      "observations": 5
    }
  },
  "buckets": [
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 27.32602466907879,
        "beta_avg": 22.53394898805574,
        "p_mean": 0.5480553370723387,
        "observations": 52
      },
      "recent": {
        "alpha_avg": 27.339469781061297,
        "beta_avg": 22.66053021889177,
        "p_mean": 0.5467893956217392,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 52
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 24.359688310565108,
        "beta_avg": 18.674995087697237,
        "p_mean": 0.5660478104400021,
        "observations": 52
      },
      "recent": {
        "alpha_avg": 26.57206458376472,
        "beta_avg": 21.282576995164952,
        "p_mean": 0.5552661916804401,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 10.911226086438118,
        "beta_avg": 15.957203852256255,
        "p_mean": 0.40609838800905873,
        "observations": 52
      },
      "recent": {
        "alpha_avg": 11.547249654774854,
        "beta_avg": 18.092316555336623,
        "p_mean": 0.38958902343299256,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 52
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 26.490793012465993,
        "beta_avg": 21.169368806836335,
        "p_mean": 0.5558267534403805,
        "observations": 52
      },
      "recent": {
        "alpha_avg": 27.288341914718462,
        "beta_avg": 22.711657773325946,
        "p_mean": 0.5457668416994695,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 52
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 52
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 52
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    }
  ]
}