{
  "meta": {
    "strategy_key": "day_orb_5m.DayORB5m",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-09-29T13:51:00Z",
    "files_total": 49,
    "recent_count": 5,
    "latest_state_ts": "2025-09-29T13:50:56Z",
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {
      "alpha_avg": 27.34702887243611,
      "beta_avg": 22.5329466045381,
      "p_mean": 0.5482566623365753,
      "observations": 49
    },
    "recent": {
      "alpha_avg": 27.263720336064416,
      "beta_avg": 22.73627966393554,
      "p_mean": 0.5452744067212888,
      "observations": 5
    }
  },
  "buckets": [
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 27.31375168396084,
        "beta_avg": 22.537648931775543,
        "p_mean": 0.5479033958243257,
        "observations": 49
      },
      "recent": {
        "alpha_avg": 27.052036034360846,
        "beta_avg": 22.94796396559304,
        "p_mean": 0.5410407206877159,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 49
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 24.35692585739816,
        "beta_avg": 18.351586764618993,
        "p_mean": 0.5703061137474884,
        "observations": 49
      },
      "recent": {
        "alpha_avg": 26.840786969614975,
        "beta_avg": 21.359536480888796,
        "p_mean": 0.556859063345859,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 10.871938503401907,
        "beta_avg": 15.818246522416906,
        "p_mean": 0.407338446432084,
        "observations": 49
      },
      "recent": {
        "alpha_avg": 11.564270518539093,
        "beta_avg": 18.49588760822359,
        "p_mean": 0.3847042477212844,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 49
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 26.38381666748798,
        "beta_avg": 21.133089763064802,
        "p_mean": 0.5552511442648025,
        "observations": 49
      },
      "recent": {
        "alpha_avg": 27.314916618506004,
        "beta_avg": 22.685083121529704,
        "p_mean": 0.5462983352104813,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 49
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 49
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 49
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    }
  ]
}