{
  "meta": {
    "strategy_key": "strategies.session_momentum_continuation.SessionMomentumContinuation",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-10-04T12:18:53Z",
    "files_total": 1,
    "recent_count": 1,
    "latest_state_ts": null,
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {
      "alpha_avg": 26.995732807504318,
      "beta_avg": 23.004267192495636,
      "p_mean": 0.5399146561500868,
      "observations": 1
    },
    "recent": {
      "alpha_avg": 26.995732807504318,
      "beta_avg": 23.004267192495636,
      "p_mean": 0.5399146561500868,
      "observations": 1
    }
  },
  "buckets": [
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 25.365162315457223,
        "beta_avg": 24.634837684541353,
        "p_mean": 0.5073032463091589,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 25.365162315457223,
        "beta_avg": 24.634837684541353,
        "p_mean": 0.5073032463091589,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 28.17651617988261,
        "beta_avg": 21.54107898243232,
        "p_mean": 0.5667312766816991,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 28.17651617988261,
        "beta_avg": 21.54107898243232,
        "p_mean": 0.5667312766816991,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 28.970693338967095,
        "beta_avg": 19.714233724504474,
        "p_mean": 0.5950649428147934,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 28.970693338967095,
        "beta_avg": 19.714233724504474,
        "p_mean": 0.5950649428147934,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 24.218547761883947,
        "beta_avg": 25.781452052111515,
        "p_mean": 0.4843709570395829,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 24.218547761883947,
        "beta_avg": 25.781452052111515,
        "p_mean": 0.4843709570395829,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      }
    }
  ]
}