{
  "meta": {
    "strategy_key": "day_orb_5m.DayORB5m",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-09-29T11:49:22Z",
    "files_total": 41,
    "recent_count": 5,
    "latest_state_ts": "2025-09-29T11:49:07Z",
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {
      "alpha_avg": 27.2977313351697,
      "beta_avg": 22.55882472267752,
      "p_mean": 0.5475254107703885,
      "observations": 41
    },
    "recent": {
      "alpha_avg": 27.265531361278356,
      "beta_avg": 22.734468638721605,
      "p_mean": 0.5453106272255676,
      "observations": 5
    }
  },
  "buckets": [
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 27.30633459817252,
        "beta_avg": 22.51607101576144,
        "p_mean": 0.5480733870974646,
        "observations": 41
      },
      "recent": {
        "alpha_avg": 26.714087630935403,
        "beta_avg": 23.285912369020064,
        "p_mean": 0.534281752619184,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 41
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 23.609480457654332,
        "beta_avg": 17.84821564554795,
        "p_mean": 0.5694836586886622,
        "observations": 41
      },
      "recent": {
        "alpha_avg": 27.242861982631773,
        "beta_avg": 21.49067488710831,
        "p_mean": 0.5590167209790098,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 10.73349153187732,
        "beta_avg": 15.216165325075934,
        "p_mean": 0.4136274938449239,
        "observations": 41
      },
      "recent": {
        "alpha_avg": 11.560732970596899,
        "beta_avg": 18.412011021967782,
        "p_mean": 0.38570819453383254,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 41
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 26.08495171391062,
        "beta_avg": 20.947448683708906,
        "p_mean": 0.5546166364757957,
        "observations": 41
      },
      "recent": {
        "alpha_avg": 27.3269551376286,
        "beta_avg": 22.673044681671335,
        "p_mean": 0.546539104727765,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 41
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 41
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 41
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    }
  ]
}