{
  "meta": {
    "strategy_key": "day_orb_5m.DayORB5m",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-09-28T21:32:14Z",
    "files_total": 29,
    "recent_count": 5,
    "latest_state_ts": "2025-09-28T21:32:04Z",
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {
      "alpha_avg": 27.11424503153552,
      "beta_avg": 22.68295491231748,
      "p_mean": 0.5444933663360026,
      "observations": 29
    },
    "recent": {
      "alpha_avg": 27.271978632711296,
      "beta_avg": 22.728021367288658,
      "p_mean": 0.5454395726542264,
      "observations": 5
    }
  },
  "buckets": [
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 27.395990427219793,
        "beta_avg": 22.35292785456334,
        "p_mean": 0.5506851480075609,
        "observations": 29
      },
      "recent": {
        "alpha_avg": 27.19307353691604,
        "beta_avg": 22.806926424366086,
        "p_mean": 0.5438614711594639,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 29
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 21.638927496071798,
        "beta_avg": 16.604461805496424,
        "p_mean": 0.5658213848526356,
        "observations": 29
      },
      "recent": {
        "alpha_avg": 21.30613606822262,
        "beta_avg": 17.335345200177606,
        "p_mean": 0.5513798997567441,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 10.377232557390874,
        "beta_avg": 13.562935187746334,
        "p_mean": 0.43346532354597744,
        "observations": 29
      },
      "recent": {
        "alpha_avg": 11.42853627982188,
        "beta_avg": 15.277577985946973,
        "p_mean": 0.4279370696196959,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 29
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 25.317216303370262,
        "beta_avg": 20.487211895435006,
        "p_mean": 0.5527242080937191,
        "observations": 29
      },
      "recent": {
        "alpha_avg": 27.254806912175063,
        "beta_avg": 22.745189709956072,
        "p_mean": 0.5450961750687692,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 29
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 29
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 29
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    }
  ]
}