{
  "meta": {
    "strategy_key": "day_orb_5m.DayORB5m",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-09-28T23:35:53Z",
    "files_total": 33,
    "recent_count": 5,
    "latest_state_ts": "2025-09-28T23:35:37Z",
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {
      "alpha_avg": 27.184202170780686,
      "beta_avg": 22.637579598059816,
      "p_mean": 0.545628863634544,
      "observations": 33
    },
    "recent": {
      "alpha_avg": 27.251241233173307,
      "beta_avg": 22.748758766826647,
      "p_mean": 0.5450248246634666,
      "observations": 5
    }
  },
  "buckets": [
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 27.30388200898546,
        "beta_avg": 22.475470420460315,
        "p_mean": 0.5484981358020742,
        "observations": 33
      },
      "recent": {
        "alpha_avg": 26.759908791299097,
        "beta_avg": 23.240091206232684,
        "p_mean": 0.5351981758524017,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 33
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 22.50211751294055,
        "beta_avg": 17.166315509641112,
        "p_mean": 0.5672550135804706,
        "observations": 33
      },
      "recent": {
        "alpha_avg": 24.75688271292985,
        "beta_avg": 19.67785996129465,
        "p_mean": 0.5571514815430834,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 10.533129730615231,
        "beta_avg": 14.445720131235943,
        "p_mean": 0.4216819344713666,
        "observations": 33
      },
      "recent": {
        "alpha_avg": 11.500414729528632,
        "beta_avg": 16.981842941582133,
        "p_mean": 0.4037746888721316,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 33
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 25.6560688734969,
        "beta_avg": 20.656913483028593,
        "p_mean": 0.5539714258950539,
        "observations": 33
      },
      "recent": {
        "alpha_avg": 27.268760360379833,
        "beta_avg": 22.73123888824036,
        "p_mean": 0.5453752154032752,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 33
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 33
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 33
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    }
  ]
}