{
  "meta": {
    "strategy_key": "day_orb_5m.DayORB5m",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-10-02T14:46:10Z",
    "files_total": 59,
    "recent_count": 5,
    "latest_state_ts": "2025-10-02T14:46:09Z",
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {
      "alpha_avg": 28.029862267622384,
      "beta_avg": 21.87045634884772,
      "p_mean": 0.5617171001062676,
      "observations": 59
    },
    "recent": {
      "alpha_avg": 27.216853047124552,
      "beta_avg": 22.783146952875406,
      "p_mean": 0.5443370609424915,
      "observations": 5
    }
  },
  "buckets": [
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 27.3606176923453,
        "beta_avg": 22.515969259705226,
        "p_mean": 0.5485663587736821,
        "observations": 59
      },
      "recent": {
        "alpha_avg": 27.167939376267366,
        "beta_avg": 22.832060623730335,
        "p_mean": 0.5433587875253724,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 59
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 24.698899476369288,
        "beta_avg": 19.02814001170642,
        "p_mean": 0.5648427098089877,
        "observations": 59
      },
      "recent": {
        "alpha_avg": 27.19216142586705,
        "beta_avg": 21.654523395167452,
        "p_mean": 0.5566838676052276,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 12.399076334230715,
        "beta_avg": 15.64961845608387,
        "p_mean": 0.44205537644169474,
        "observations": 59
      },
      "recent": {
        "alpha_avg": 11.559181089386747,
        "beta_avg": 18.375215337411987,
        "p_mean": 0.38615046465538233,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 59
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 26.586842314282723,
        "beta_avg": 21.350927395750425,
        "p_mean": 0.5546115823723485,
        "observations": 59
      },
      "recent": {
        "alpha_avg": 27.31063434641074,
        "beta_avg": 22.68936540332742,
        "p_mean": 0.5462126896621387,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 59
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 59
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 59
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 5
      }
    }
  ]
}