{
  "meta": {
    "strategy_key": "reversion_stub.MeanReversionStrategy",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-09-29T00:00:40Z",
    "files_total": 4,
    "recent_count": 4,
    "latest_state_ts": "2025-09-29T00:00:30Z",
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {
      "alpha_avg": 13.266591468949137,
      "beta_avg": 26.51010171561769,
      "p_mean": 0.3335267566710778,
      "observations": 4
    },
    "recent": {
      "alpha_avg": 13.266591468949137,
      "beta_avg": 26.51010171561769,
      "p_mean": 0.3335267566710778,
      "observations": 4
    }
  },
  "buckets": [
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 0.9557440199999999,
        "beta_avg": 3.1685430200000004,
        "p_mean": 0.23173557289552763,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 0.9557440199999999,
        "beta_avg": 3.1685430200000004,
        "p_mean": 0.23173557289552763,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 5.333141790478523,
        "beta_avg": 16.092541392084456,
        "p_mean": 0.24891349998206047,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 5.333141790478523,
        "beta_avg": 16.092541392084456,
        "p_mean": 0.24891349998206047,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 5.07378693682555,
        "beta_avg": 2.9734727196518502,
        "p_mean": 0.6304987229710621,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 5.07378693682555,
        "beta_avg": 2.9734727196518502,
        "p_mean": 0.6304987229710621,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 12.0245149680508,
        "beta_avg": 20.09615474630757,
        "p_mean": 0.3743544289388113,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 12.0245149680508,
        "beta_avg": 20.09615474630757,
        "p_mean": 0.3743544289388113,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      }
    }
  ]
}