{
  "meta": {
    "strategy_key": "strategies.day_orb_5m.DayORB5m",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-10-09T15:12:26Z",
    "files_total": 4,
    "recent_count": 4,
    "latest_state_ts": null,
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {
      "alpha_avg": 25.762842341135443,
      "beta_avg": 24.237157410905166,
      "p_mean": 0.5152568493779643,
      "observations": 4
    },
    "recent": {
      "alpha_avg": 25.762842341135443,
      "beta_avg": 24.237157410905166,
      "p_mean": 0.5152568493779643,
      "observations": 4
    }
  },
  "buckets": [
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.865842380864,
        "beta_avg": 5.613723337663999,
        "p_mean": 0.24945865188964517,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 1.865842380864,
        "beta_avg": 5.613723337663999,
        "p_mean": 0.24945865188964517,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 28.69572725204131,
        "beta_avg": 21.303060183316514,
        "p_mean": 0.5739284635480669,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 28.69572725204131,
        "beta_avg": 21.303060183316514,
        "p_mean": 0.5739284635480669,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 24.39130927264427,
        "beta_avg": 20.35327223440808,
        "p_mean": 0.5451231959516678,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 24.39130927264427,
        "beta_avg": 20.35327223440808,
        "p_mean": 0.5451231959516678,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 24.09331469056019,
        "beta_avg": 25.805482091107834,
        "p_mean": 0.4828436003373065,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 24.09331469056019,
        "beta_avg": 25.805482091107834,
        "p_mean": 0.4828436003373065,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 4
      }
    }
  ]
}