{
  "meta": {
    "strategy_key": "strategies.dummy.DummyStrategy",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-09-29T11:48:04Z",
    "files_total": 1,
    "recent_count": 1,
    "latest_state_ts": "2025-09-29T11:48:04Z",
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {}
  },
  "buckets": []
}