{
  "meta": {
    "strategy_key": "strategies.day_orb_5m.DayORB5m",
    "symbol": "USDJPY",
    "mode": "conservative",
    "generated_at": "2025-10-01T12:22:07Z",
    "files_total": 1,
    "recent_count": 1,
    "latest_state_ts": "2025-10-01T12:22:07Z",
    "alpha_prior": 1.0,
    "beta_prior": 1.0
  },
  "global": {
    "long_term": {
      "alpha_avg": 27.090549067301946,
      "beta_avg": 22.909450671959895,
      "p_mean": 0.5418109841714549,
      "observations": 1
    },
    "recent": {
      "alpha_avg": 27.090549067301946,
      "beta_avg": 22.909450671959895,
      "p_mean": 0.5418109841714549,
      "observations": 1
    }
  },
  "buckets": [
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.865842380864,
        "beta_avg": 5.613723337663999,
        "p_mean": 0.24945865188964517,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 1.865842380864,
        "beta_avg": 5.613723337663999,
        "p_mean": 0.24945865188964517,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "LDN",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 28.69572725204131,
        "beta_avg": 21.303060183316514,
        "p_mean": 0.5739284635480669,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 28.69572725204131,
        "beta_avg": 21.303060183316514,
        "p_mean": 0.5739284635480669,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 25.64833304946524,
        "beta_avg": 18.8254066618911,
        "p_mean": 0.5767073607015771,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 25.64833304946524,
        "beta_avg": 18.8254066618911,
        "p_mean": 0.5767073607015771,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "NY",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 24.09331469056019,
        "beta_avg": 25.805482091107834,
        "p_mean": 0.4828436003373065,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 24.09331469056019,
        "beta_avg": 25.805482091107834,
        "p_mean": 0.4828436003373065,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "high"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "low"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      }
    },
    {
      "bucket": {
        "session": "TOK",
        "spread_band": "narrow",
        "rv_band": "mid"
      },
      "long_term": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      },
      "recent": {
        "alpha_avg": 1.0,
        "beta_avg": 1.0,
        "p_mean": 0.5,
        "observations": 1
      }
    }
  ]
}