meta:
  id: day_orb_5m_v1
  name: Day ORB 5m (USDJPY)
  version: "1.0"
  category: day
  tags: [orb, breakout]
  description: |
    Opening range breakout strategy for USDJPY 5m bars. Trades LDN/NY sessions
    with ATR-based exits and simple risk filters.

strategy:
  class_path: strategies.day_orb_5m.DayORB5m
  instruments:
    - symbol: USDJPY
      timeframe: 5m
      mode: conservative
    - symbol: USDJPY
      timeframe: 5m
      mode: bridge
  parameters:
    or_n: 6
    k_tp: 1.5
    k_sl: 0.6
    k_tr: 0.4
    require_close_breakout: false
    require_retest: true
    retest_max_bars: 4
    retest_tol_k: 0.2
    min_or_atr_ratio: 0.6
    cooldown_bars: 2
    min_micro_trend: 0.25
    min_atr_pips: 3.0
    max_atr_pips: 35.0
    max_signals_per_day: 4
    fallback_win_rate: 0.55

router:
  allowed_sessions: [LDN, NY]
  allow_spread_bands: [narrow, normal]
  allow_rv_bands: [mid, high]
  max_latency_ms: 80
  category_cap_pct: 40
  tags: [breakout, usd, jpy]

risk:
  risk_per_trade_pct: 0.25
  max_daily_dd_pct: 5.0
  notional_cap: 2000000
  max_concurrent_positions: 1
  warmup_trades: 0

features:
  required: [atr14, adx14, rv12, or_high, or_low, spread_band, session]
  optional: [regime_flag]

runner:
  runner_config:
    threshold_lcb_pip: -10.0
    min_or_atr_ratio: 0.6
    allowed_sessions: [LDN, NY]
    warmup_trades: 0
    include_expected_slip: true
  cli_args:
    equity: 100000
    threshold_lcb: -10.0
    min_or_atr: 0.6
    allowed_sessions: LDN,NY
    ev_mode: off
    auto_state: false
    aggregate_ev: false
    use_ev_profile: false

state:
  ev_profile: null

notes:
  - Disable during Tokyo session due to low OR quality.
  - Requires validated/USDJPY/5m.csv ingestion pipeline.
