# Weekly observability payload configuration.
# Webhook destinations are populated via environment variables referenced by
# ``run_daily_workflow.py --observability``. Toggle ``destinations.dry_run`` or
# supply ``--dry-run`` to the workflow for rehearsals that skip webhook posts.
include:
  - runs
  - benchmarks
  - portfolio
  - health
destinations:
  webhooks: []
  fail_on_error: true
  dry_run: false
