name: Day ORB Optimisation Bundle

on:
  schedule:
    - cron: '0 5 * * 1-5'
    - cron: '30 6 * * 1'
  workflow_dispatch:

jobs:
  dry-run:
    if: github.event_name != 'schedule' || github.event.schedule == '0 5 * * 1-5'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          python -m pip install pytest pyyaml pandas

      - name: Run Day ORB bundle (dry-run)
        run: |
          python scripts/run_daily_workflow.py \
            --day-orb-optimization \
            --day-orb-config configs/day_orb/optimization_bundle.yaml \
            --day-orb-dry-run \
            --day-orb-output reports/day_orb/ci/day_orb_bundle_dry_run.json

  production:
    if: github.event_name != 'schedule' || github.event.schedule == '30 6 * * 1'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          python -m pip install pytest pyyaml pandas

      - name: Run Day ORB bundle (production)
        run: |
          python scripts/run_daily_workflow.py \
            --day-orb-optimization \
            --day-orb-config configs/day_orb/optimization_bundle.yaml \
            --day-orb-output reports/day_orb/ci/day_orb_bundle_production.json
